// Try Catch Error Final
function div(a, b) {
  return a / b;
}
try {
} catch (e) {
} finally {
}
